[package]
name = "minus1"
version = "0.1.0"
edition = "2021"

[lib]
name = "minus1_endpoint"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }

